from bs4 import BeautifulSoup
import requests

#
req = requests.get("URL_OF_THE_PAGE_THAT_YOU_WANT_TO_GET_ELEMENTS")

# YOU USE THE METHOD BELOW THAT TAKES TWO ARGUMENTS TO MAKE YOUR SOUP
soup = BeautifulSoup(req.content, "html.parser")

# AT THE MOMENT PRINTING THE SOUP WON'T BE A GOOD IDEA BECAUSE IT LOOKS MESSY
# BUT FEEL FREE TO TRY
# AS WE ALL KNOW THE MORE YOU F AROUND THE MORE YOU FIND OUT
print(soup)

# NOW WE TRY TO FILTER TROUGH THE ELEMENTS FOR MORE FUNCTIONALITY
res_1 = soup.find(id="ID_OF_AN_ELEMENT")s


# ANOTHER MORE SPECIFIC WAY IS TO GET ONE OR MULTIPLE ELEMENTS AND FILTER IT BY CLASS OR ID
res_2 = soup.find_all("div", class_="CLASS_OF_AN_ELEMENT")

# res VARIABLE CAN BE ITERATED WITH FOR LOOP IF THERE ARE MULTIPLE ELEMENTS WITH THE SPECIFICATION
for final_result in res_2:
    print(final_result.text)
    # BY USING .text YOU ONLY GET THE INNERHTML(THE CONTENT) OF AN ELEMENT WHICH THE WHOLE IDEA WAS BEING ABLE TO GET THE CONTENT FROM A WEB-PAGE
